version: '3.3'
services:

  myapp:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - my_net
    depends_on:
      - otel_collector
    environment:
      - CONFIG_DIR=/app/config
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel_collector:4317

  # OpenTelemetry Collector
  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.70.0
    command: --config=/etc/otel-collector-config.yaml
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP over gRPC receiver
      - "9464:9464" # Prometheus exporter
    depends_on:
      - jaeger
      - prometheus
    networks:
      - my_net

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.41.0
    ports:
      - "14250:14250" # Collector gRPC
      - "16686:16686" # Web HTTP
    volumes:
      - jaeger_data:/data
    networks:
      - my_net

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.42.0
    command:
      - --config.file=/etc/prometheus/prometheus-config.yaml
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - my_net

  # Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - my_net

networks:
  my_net:

volumes:
  prometheus_data:
  grafana_data:
  jaeger_data: