{
 "title": "Go Concurrency",
 "description": "Dashboard for Operating Systems final project",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_count) by (http_route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route) (rate(histogram_quantile(0.95, sum(rate(request_response_time_bucket[5m])) by (le))[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed products",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "products_processed_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "concurrent_workers_gauge", "legendFormat": "__auto" }
   ]
  }
 ]
}